const ShopeActionTypes = {
  GET_COLLECTION_START: "GET_COLLECTION_START",
  GET_COLLECTION_SUCCESS: "GET_COLLECTION_SUCCESS",
  GET_COLLECTION_ERROR: "GET_COLLECTION_ERROR",
};

export default ShopeActionTypes;
